//! Embedded World Magnetic Model Gauss coefficients.
//!
//! Values are the WMM-2025 main-field coefficients (nT) and secular-variation
//! coefficients (nT/year) published by NOAA/NCEI in `WMM2025.COF`, dated
//! 2024-11-13. The WMM model epoch is 2025.0.

pub(super) const WMM_MODEL_EPOCH: f64 = 2025.0;
pub(super) const WMM_MAX_DEGREE: usize = 12;

#[derive(Clone, Copy, Debug)]
pub(super) struct WmmCoefficient {
    pub n: usize,
    pub m: usize,
    pub g_nt: f64,
    pub h_nt: f64,
    pub g_dot_nt_per_year: f64,
    pub h_dot_nt_per_year: f64,
}

pub(super) const WMM_COEFFICIENTS: &[WmmCoefficient] = &[
    WmmCoefficient {
        n: 1,
        m: 0,
        g_nt: -29351.8,
        h_nt: 0.0,
        g_dot_nt_per_year: 12.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 1,
        m: 1,
        g_nt: -1410.8,
        h_nt: 4545.4,
        g_dot_nt_per_year: 9.7,
        h_dot_nt_per_year: -21.5,
    },
    WmmCoefficient {
        n: 2,
        m: 0,
        g_nt: -2556.6,
        h_nt: 0.0,
        g_dot_nt_per_year: -11.6,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 2,
        m: 1,
        g_nt: 2951.1,
        h_nt: -3133.6,
        g_dot_nt_per_year: -5.2,
        h_dot_nt_per_year: -27.7,
    },
    WmmCoefficient {
        n: 2,
        m: 2,
        g_nt: 1649.3,
        h_nt: -815.1,
        g_dot_nt_per_year: -8.0,
        h_dot_nt_per_year: -12.1,
    },
    WmmCoefficient {
        n: 3,
        m: 0,
        g_nt: 1361.0,
        h_nt: 0.0,
        g_dot_nt_per_year: -1.3,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 3,
        m: 1,
        g_nt: -2404.1,
        h_nt: -56.6,
        g_dot_nt_per_year: -4.2,
        h_dot_nt_per_year: 4.0,
    },
    WmmCoefficient {
        n: 3,
        m: 2,
        g_nt: 1243.8,
        h_nt: 237.5,
        g_dot_nt_per_year: 0.4,
        h_dot_nt_per_year: -0.3,
    },
    WmmCoefficient {
        n: 3,
        m: 3,
        g_nt: 453.6,
        h_nt: -549.5,
        g_dot_nt_per_year: -15.6,
        h_dot_nt_per_year: -4.1,
    },
    WmmCoefficient {
        n: 4,
        m: 0,
        g_nt: 895.0,
        h_nt: 0.0,
        g_dot_nt_per_year: -1.6,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 4,
        m: 1,
        g_nt: 799.5,
        h_nt: 278.6,
        g_dot_nt_per_year: -2.4,
        h_dot_nt_per_year: -1.1,
    },
    WmmCoefficient {
        n: 4,
        m: 2,
        g_nt: 55.7,
        h_nt: -133.9,
        g_dot_nt_per_year: -6.0,
        h_dot_nt_per_year: 4.1,
    },
    WmmCoefficient {
        n: 4,
        m: 3,
        g_nt: -281.1,
        h_nt: 212.0,
        g_dot_nt_per_year: 5.6,
        h_dot_nt_per_year: 1.6,
    },
    WmmCoefficient {
        n: 4,
        m: 4,
        g_nt: 12.1,
        h_nt: -375.6,
        g_dot_nt_per_year: -7.0,
        h_dot_nt_per_year: -4.4,
    },
    WmmCoefficient {
        n: 5,
        m: 0,
        g_nt: -233.2,
        h_nt: 0.0,
        g_dot_nt_per_year: 0.6,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 5,
        m: 1,
        g_nt: 368.9,
        h_nt: 45.4,
        g_dot_nt_per_year: 1.4,
        h_dot_nt_per_year: -0.5,
    },
    WmmCoefficient {
        n: 5,
        m: 2,
        g_nt: 187.2,
        h_nt: 220.2,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 2.2,
    },
    WmmCoefficient {
        n: 5,
        m: 3,
        g_nt: -138.7,
        h_nt: -122.9,
        g_dot_nt_per_year: 0.6,
        h_dot_nt_per_year: 0.4,
    },
    WmmCoefficient {
        n: 5,
        m: 4,
        g_nt: -142.0,
        h_nt: 43.0,
        g_dot_nt_per_year: 2.2,
        h_dot_nt_per_year: 1.7,
    },
    WmmCoefficient {
        n: 5,
        m: 5,
        g_nt: 20.9,
        h_nt: 106.1,
        g_dot_nt_per_year: 0.9,
        h_dot_nt_per_year: 1.9,
    },
    WmmCoefficient {
        n: 6,
        m: 0,
        g_nt: 64.4,
        h_nt: 0.0,
        g_dot_nt_per_year: -0.2,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 6,
        m: 1,
        g_nt: 63.8,
        h_nt: -18.4,
        g_dot_nt_per_year: -0.4,
        h_dot_nt_per_year: 0.3,
    },
    WmmCoefficient {
        n: 6,
        m: 2,
        g_nt: 76.9,
        h_nt: 16.8,
        g_dot_nt_per_year: 0.9,
        h_dot_nt_per_year: -1.6,
    },
    WmmCoefficient {
        n: 6,
        m: 3,
        g_nt: -115.7,
        h_nt: 48.8,
        g_dot_nt_per_year: 1.2,
        h_dot_nt_per_year: -0.4,
    },
    WmmCoefficient {
        n: 6,
        m: 4,
        g_nt: -40.9,
        h_nt: -59.8,
        g_dot_nt_per_year: -0.9,
        h_dot_nt_per_year: 0.9,
    },
    WmmCoefficient {
        n: 6,
        m: 5,
        g_nt: 14.9,
        h_nt: 10.9,
        g_dot_nt_per_year: 0.3,
        h_dot_nt_per_year: 0.7,
    },
    WmmCoefficient {
        n: 6,
        m: 6,
        g_nt: -60.7,
        h_nt: 72.7,
        g_dot_nt_per_year: 0.9,
        h_dot_nt_per_year: 0.9,
    },
    WmmCoefficient {
        n: 7,
        m: 0,
        g_nt: 79.5,
        h_nt: 0.0,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 7,
        m: 1,
        g_nt: -77.0,
        h_nt: -48.9,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.6,
    },
    WmmCoefficient {
        n: 7,
        m: 2,
        g_nt: -8.8,
        h_nt: -14.4,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.5,
    },
    WmmCoefficient {
        n: 7,
        m: 3,
        g_nt: 59.3,
        h_nt: -1.0,
        g_dot_nt_per_year: 0.5,
        h_dot_nt_per_year: -0.8,
    },
    WmmCoefficient {
        n: 7,
        m: 4,
        g_nt: 15.8,
        h_nt: 23.4,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 7,
        m: 5,
        g_nt: 2.5,
        h_nt: -7.4,
        g_dot_nt_per_year: -0.8,
        h_dot_nt_per_year: -1.0,
    },
    WmmCoefficient {
        n: 7,
        m: 6,
        g_nt: -11.1,
        h_nt: -25.1,
        g_dot_nt_per_year: -0.8,
        h_dot_nt_per_year: 0.6,
    },
    WmmCoefficient {
        n: 7,
        m: 7,
        g_nt: 14.2,
        h_nt: -2.3,
        g_dot_nt_per_year: 0.8,
        h_dot_nt_per_year: -0.2,
    },
    WmmCoefficient {
        n: 8,
        m: 0,
        g_nt: 23.2,
        h_nt: 0.0,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 8,
        m: 1,
        g_nt: 10.8,
        h_nt: 7.1,
        g_dot_nt_per_year: 0.2,
        h_dot_nt_per_year: -0.2,
    },
    WmmCoefficient {
        n: 8,
        m: 2,
        g_nt: -17.5,
        h_nt: -12.6,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.5,
    },
    WmmCoefficient {
        n: 8,
        m: 3,
        g_nt: 2.0,
        h_nt: 11.4,
        g_dot_nt_per_year: 0.5,
        h_dot_nt_per_year: -0.4,
    },
    WmmCoefficient {
        n: 8,
        m: 4,
        g_nt: -21.7,
        h_nt: -9.7,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.4,
    },
    WmmCoefficient {
        n: 8,
        m: 5,
        g_nt: 16.9,
        h_nt: 12.7,
        g_dot_nt_per_year: 0.3,
        h_dot_nt_per_year: -0.5,
    },
    WmmCoefficient {
        n: 8,
        m: 6,
        g_nt: 15.0,
        h_nt: 0.7,
        g_dot_nt_per_year: 0.2,
        h_dot_nt_per_year: -0.6,
    },
    WmmCoefficient {
        n: 8,
        m: 7,
        g_nt: -16.8,
        h_nt: -5.2,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.3,
    },
    WmmCoefficient {
        n: 8,
        m: 8,
        g_nt: 0.9,
        h_nt: 3.9,
        g_dot_nt_per_year: 0.2,
        h_dot_nt_per_year: 0.2,
    },
    WmmCoefficient {
        n: 9,
        m: 0,
        g_nt: 4.6,
        h_nt: 0.0,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 9,
        m: 1,
        g_nt: 7.8,
        h_nt: -24.8,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.3,
    },
    WmmCoefficient {
        n: 9,
        m: 2,
        g_nt: 3.0,
        h_nt: 12.2,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: 0.3,
    },
    WmmCoefficient {
        n: 9,
        m: 3,
        g_nt: -0.2,
        h_nt: 8.3,
        g_dot_nt_per_year: 0.3,
        h_dot_nt_per_year: -0.3,
    },
    WmmCoefficient {
        n: 9,
        m: 4,
        g_nt: -2.5,
        h_nt: -3.3,
        g_dot_nt_per_year: -0.3,
        h_dot_nt_per_year: 0.3,
    },
    WmmCoefficient {
        n: 9,
        m: 5,
        g_nt: -13.1,
        h_nt: -5.2,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.2,
    },
    WmmCoefficient {
        n: 9,
        m: 6,
        g_nt: 2.4,
        h_nt: 7.2,
        g_dot_nt_per_year: 0.3,
        h_dot_nt_per_year: -0.1,
    },
    WmmCoefficient {
        n: 9,
        m: 7,
        g_nt: 8.6,
        h_nt: -0.6,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.2,
    },
    WmmCoefficient {
        n: 9,
        m: 8,
        g_nt: -8.7,
        h_nt: 0.8,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: 0.4,
    },
    WmmCoefficient {
        n: 9,
        m: 9,
        g_nt: -12.9,
        h_nt: 10.0,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 10,
        m: 0,
        g_nt: -1.3,
        h_nt: 0.0,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 10,
        m: 1,
        g_nt: -6.4,
        h_nt: 3.3,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 10,
        m: 2,
        g_nt: 0.2,
        h_nt: 0.0,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 10,
        m: 3,
        g_nt: 2.0,
        h_nt: 2.4,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: -0.2,
    },
    WmmCoefficient {
        n: 10,
        m: 4,
        g_nt: -1.0,
        h_nt: 5.3,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 10,
        m: 5,
        g_nt: -0.6,
        h_nt: -9.1,
        g_dot_nt_per_year: -0.3,
        h_dot_nt_per_year: -0.1,
    },
    WmmCoefficient {
        n: 10,
        m: 6,
        g_nt: -0.9,
        h_nt: 0.4,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 10,
        m: 7,
        g_nt: 1.5,
        h_nt: -4.2,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 10,
        m: 8,
        g_nt: 0.9,
        h_nt: -3.8,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.1,
    },
    WmmCoefficient {
        n: 10,
        m: 9,
        g_nt: -2.7,
        h_nt: 0.9,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.2,
    },
    WmmCoefficient {
        n: 10,
        m: 10,
        g_nt: -3.9,
        h_nt: -9.1,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 0,
        g_nt: 2.9,
        h_nt: 0.0,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 1,
        g_nt: -1.5,
        h_nt: 0.0,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 2,
        g_nt: -2.5,
        h_nt: 2.9,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 11,
        m: 3,
        g_nt: 2.4,
        h_nt: -0.6,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 4,
        g_nt: -0.6,
        h_nt: 0.2,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 11,
        m: 5,
        g_nt: -0.1,
        h_nt: 0.5,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 6,
        g_nt: -0.6,
        h_nt: -0.3,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 7,
        g_nt: -0.1,
        h_nt: -1.2,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 11,
        m: 8,
        g_nt: 1.1,
        h_nt: -1.7,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 9,
        g_nt: -1.0,
        h_nt: -2.9,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 10,
        g_nt: -0.2,
        h_nt: -1.8,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 11,
        m: 11,
        g_nt: 2.6,
        h_nt: -2.3,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 0,
        g_nt: -2.0,
        h_nt: 0.0,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 1,
        g_nt: -0.2,
        h_nt: -1.3,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 2,
        g_nt: 0.3,
        h_nt: 0.7,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 3,
        g_nt: 1.2,
        h_nt: 1.0,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: -0.1,
    },
    WmmCoefficient {
        n: 12,
        m: 4,
        g_nt: -1.3,
        h_nt: -1.4,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.1,
    },
    WmmCoefficient {
        n: 12,
        m: 5,
        g_nt: 0.6,
        h_nt: -0.0,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 6,
        g_nt: 0.6,
        h_nt: 0.6,
        g_dot_nt_per_year: 0.1,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 7,
        g_nt: 0.5,
        h_nt: -0.1,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 8,
        g_nt: -0.1,
        h_nt: 0.8,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 9,
        g_nt: -0.4,
        h_nt: 0.1,
        g_dot_nt_per_year: 0.0,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 10,
        g_nt: -0.2,
        h_nt: -1.0,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 11,
        g_nt: -1.3,
        h_nt: 0.1,
        g_dot_nt_per_year: -0.0,
        h_dot_nt_per_year: 0.0,
    },
    WmmCoefficient {
        n: 12,
        m: 12,
        g_nt: -0.7,
        h_nt: 0.2,
        g_dot_nt_per_year: -0.1,
        h_dot_nt_per_year: -0.1,
    },
];
